services:
  - type: web
    name: perfumeria-burbujita
    runtime: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: BURBUJITA_ADMIN_USER
        sync: false
      - key: BURBUJITA_ADMIN_PASSWORD
        sync: false
